# Format StarShip Promt
format = """
$hostname\
$username\
$localip\
$directory\
$singularity\
$kubernetes\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$shell\
$status\
$character"""


# Exit Code Command Configuration Promt
[status]
format = "[$symbol $status]($style) "
disabled = false


# Actual User Promt
[username]
show_always = true
format = "with [$user]($style) in "


# Local IP Promt
# [localip]
# ssh_only = false
# disabled = true

# Clock Time Promt
[time]
disabled = false

# Hostname Promt
[hostname]
format = "[$hostname](bold red) "
ssh_only = false
disabled = false

# Shell Indicator Configuration Promt
[shell]
format = "with [$indicator]($style) "
fish_indicator = ""
powershell_indicator = "_"
unknown_indicator = "?"
disabled = false

# Sudo Password Cached Configuration Promt
[sudo]
format="[sudo $symbol cached ](bold red)"
style = "#cc0066"
symbol = "ﳳ"
disabled = false

# Battery Status Promt
[battery]
charging_symbol = " "

[[battery.display]]
threshold = 10
style = "#ff0000"
discharging_symbol=" "

[[battery.display]]
threshold = 20
style = "#ff5050"
discharging_symbol=" "

[[battery.display]]
threshold = 30
style = "#ff6600"
discharging_symbol=" "

[[battery.display]]
threshold = 40
style = "#ff9933"
discharging_symbol=" "

[[battery.display]]
threshold = 50
style = "#ffcc00"
discharging_symbol=" "

[[battery.display]]
threshold = 60
style = "#ffff66"
discharging_symbol=" "

[[battery.display]]
threshold = 70
style = "#ccff66"
discharging_symbol=" "

[[battery.display]]
threshold = 80
style = "#99ff66"
discharging_symbol=" "

[[battery.display]]
threshold = 90
style = "#66ff66"
discharging_symbol=" "

[[battery.display]]
threshold = 100
style = "#00ff00"
discharging_symbol=" "


# Direcoty Configuration Promt
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = "  "
read_only_style = "#ff3300"


# Google Cloud Configuration Promt
[gcloud]
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '
symbol = "   "

# Git Configuration Promt
[git_branch]
symbol = " "
always_show_remote = true

# Memory Usage 
[memory_usage]
format = "[ $symbol : $ram_pct ]($style)"
threshold = 50
disabled = false
symbol = ""


# Nerd Font Simbol Replacement of emogis 
[aws]
symbol = "   "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
