# Format StarShip Promt
format = """
$hostname with $username in $directory\
$singularity\
$kubernetes\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$memory_usage\
$line_break\
$battery with $sudo $shell $line_break\
$status\
$cmd_duration\
$character\
"""

# Exit Code Command Configuration Promt
[status]
symbol = ""
format = "[$symbol $status ]($style)"
disabled = false

# CMD Duration
[cmd_duration]
format = "[󱦟 $duration ](bold blue)"

# Actual User Promt
[username]
show_always = true
<<<<<<< HEAD
format = "with [$user]($style) in "


# Local IP Promt
# [localip]
# ssh_only = false
# disabled = true

# Clock Time Promt
[time]
disabled = false
=======
format = "[<$user/>]($style)"
style = 'bright-yellow'
>>>>>>> 9820523 (Updated Starship Promt)

# Hostname Promt
[hostname]
format = "[$hostname]($style)"
style = 'blue'
ssh_only = false
disabled = false
ssh_symbol = " "

# Shell Indicator Configuration Promt
[shell]
format = "[$indicator]($style)"
fish_indicator = "󰈺 "
nu_indicator = "nu"
powershell_indicator = "󰨊 "
unknown_indicator = ""
disabled = false

# Sudo Password Cached Configuration Promt
[sudo]
format="[sudo]($style)"
style = "red"
symbol = ""
disabled = false

# Battery Status Promt
[battery]
format = "[$symbol$percentage]($style)"
charging_symbol = "󰂄"

[[battery.display]]
threshold = 10
style = "#ff0000"
discharging_symbol="󰁺"

[[battery.display]]
threshold = 20
style = "#ff5050"
discharging_symbol="󰁻"

[[battery.display]]
threshold = 30
style = "#ff6600"
discharging_symbol="󰁼"

[[battery.display]]
threshold = 40
style = "#ff9933"
discharging_symbol="󰁽"

[[battery.display]]
threshold = 50
style = "#ffcc00"
discharging_symbol="󰁾"

[[battery.display]]
threshold = 60
style = "#ffff66"
discharging_symbol="󰁿"

[[battery.display]]
threshold = 70
style = "#ccff66"
discharging_symbol="󰂀"

[[battery.display]]
threshold = 80
style = "#99ff66"
discharging_symbol="󰂁"

[[battery.display]]
threshold = 90
style = "#66ff66"
discharging_symbol="󰂂"

[[battery.display]]
threshold = 100
style = "#00ff00"
discharging_symbol="󰁹 "


# Direcoty Configuration Promt
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_symbol = "󰍻 /"
read_only = " 󰏮 "
home_symbol = '󱂶'
read_only_style = "bold red"
style = "bright-blue"

# Google Cloud Configuration Promt
[gcloud]
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '
symbol = "   "

# Git Configuration Promt
[git_branch]
symbol = " "
always_show_remote = true

# Memory Usage 
[memory_usage]
format = "[ $symbol : $ram_pct ]($style)"
threshold = 50
disabled = false
symbol = "󰍛"

# Nerd Font Simbol Replacement of Emoji
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
